/**
 * Czech microcopy for Weelio app
 * Structured for future i18n support
 */

export const cs = {
  common: {
    saved: "Uloženo",
    savedCheck: "Uloženo ✅",
    deleted: "Smazáno",
    login: "Přihlásit se",
    browse: "Procházet",
    cancel: "Zrušit",
    delete: "Smazat",
    deleting: "Mazání...",
    todayDone: "✓ Dnes hotovo",
    done: "Hotovo",
    saving: "Ukládám...",
    checking: "Kontroluji...",
  },
  place: {
    hints: {
      visitAlready: "Dnes už máš zapsáno 🙃",
      journalAlready: "Už jsi dnes zapsal 😉",
      riddlesNone: "Kešky zatím nejsou 🥲",
      riddlesDown: "Hádanky dole 👇",
      riddlesNoAttempts: "Dnes už nemáš pokusy 😅",
      visitLogged: "Návštěva zaznamenána ✅",
    },
    actionbar: {
      visit: "Visit",
      journal: "Zapsat",
      journalDone: "✓ Zapsáno",
      riddle: "Keška",
    },
    daily: {
      title: "Dnes na tomhle místě",
      visitLabel: "Návštěva",
      visitedStatus: "✓ Navštíveno",
      notVisitedStatus: "○ Navštívit",
      journalLabel: "Zápis",
      journalSavedStatus: "✓ Zapsáno",
      journalNotSavedStatus: "○ Zapsat",
      riddlesLabel: "Kešky",
      riddlesDoneToday: "Kešky (dnes hotovo)",
      riddlesCta: "Na kešky",
      journalCta: "Napsat",
      infoPopover: {
        trigger: "Co to znamená?",
        title: "3 rychlé akce na místě",
        visitExplain: "Navštívit: zaznamená návštěvu, získáš XP a streak 🔥",
        journalExplain: "Zapsat: krátký zápis pro ostatní návštěvníky ✍️",
        riddlesExplain: "Kešky: vyřeš hádanky na místě a získej odměny XP 🎯",
      },
    },
  },
  visit: {
    button: {
      default: "Byl jsem tady",
      compact: "Visit",
      recording: "Zaznamenávám…",
      todayDone: "✓ Dnes už máš hotovo",
    },
    toast: {
      alreadyVisited: "Dnes už máš zapsáno 🙃",
      mustLogin: "Musíš být přihlášen",
      failed: "Nepodařilo se zapsat návštěvu",
      recorded: "Návštěva zaznamenána ✅",
    },
  },
  journal: {
    quickModal: {
      title: "Rychlý zápis",
      description: "Klidně jen 1 věta. Soukromé zůstane jen pro tebe.",
      contentLabel: "Obsah záznamu",
      contentPlaceholder: "Tvůj zážitek z tohoto místa...",
      visibilityLabel: "Viditelnost",
      visibilityPrivate: "Soukromý",
      visibilityPrivateDesc: "Jen pro tebe",
      visibilityPublic: "Veřejný",
      visibilityPublicDesc: "Uvidí všichni",
      save: "Uložit",
      saving: "Ukládám...",
      emptyError: "Obsah nesmí být prázdný",
      tooLongError: "Obsah je příliš dlouhý (maximum 2000 znaků)",
      charCount: (count: number) => `${count} / 2000 znaků`,
    },
    section: {
      title: "Zápisy z cesty",
      empty: "Nikdo ještě nic nezapsal",
      emptyAction: "Přihlaš se a buď první",
      deleteConfirm: "Jsi si jistý?",
      deleteDesc: "Záznam bude nenávratně smazán.",
      deleteCancel: "Zpět",
      deleteConfirmButton: "Ano, smazat",
    },
    placeSection: {
      title: "Deník místa",
      description: "Veřejné zápisky od návštěvníků",
      addButton: "Napsat zápis",
      emptyTitle: "Zatím žádné veřejné zápisky k tomuto místu.",
      emptyDesc: "Buď první – stačí 1 věta a ostatním to pomůže.",
      addFirstButton: "Napsat první zápis",
    },
  },
  riddles: {
    title: "Kešky",
    titleOnPlace: "Kešky na místě",
    description: "Vyřeš hádanky a získej XP body",
    loginPrompt: "Přihlaš se pro řešení kešek",
    loginDesc: "Získej XP body za správné odpovědi.",
    addRiddle: "Přidat kešku",
    inputPlaceholderText: "Zadej odpověď...",
    inputPlaceholderNumber: "Zadej číslo...",
    submitButton: "Zkusit",
    solved: "✅ Splněno",
    checking: "Kontroluji...",
    correct: "Správně! 🎉",
    correctWithXp: (xp: number) => `Správně! +${xp} XP 🎉`,
    incorrect: "Zkus to znovu",
    emptyAnswer: "Zadej odpověď",
    verifyFailed: "Nepodařilo se ověřit odpověď",
    noAttemptsLeft: "Dnes už žádné pokusy",
    badge: {
      remaining: (remaining: number, limit: number) => `${remaining}/${limit}`,
    },
    attempts: {
      limit: 5,
      singular: "pokus",
      few: "pokusy",
      many: "pokusů",
    },
  },
} as const;
